services:
  - type: web
    name: elpatron
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8080
    regions:
      - oregon
    healthCheckPath: /
    autoDeploy: true